### ISSUE TITLE
Development roadmap/plan for this plugin

### ISSUE THREAD

**Issue by cp2004** [cp2004/OctoPrint-EEPROM-Marlin#1]
I will be documenting my initial plans for development of this plugin in this ticket - please don't open issues for features that I already have on this list!

* [x] Python 3 compatibility
* [x] Fix some UI issues
* [x] Move tab from settings to its own tab
* [x] Add new maintainer dialog
* [x] Work out observed performance issues:
    * [x] ~~Issue commands on tab click (not app startup) to speed up load times~~ Not required - re-written version will not need to do this at all. Requests are async, and parsing is done server side.
    * [x] Send data to server, for persistence - means reloading does not have to parse all the data again, sending M5xx commands
* [x] Utilise server side 
    * Allows for a more powerful implementation, where data is persisted across reloads.
    * Should allow you to view settings while the printer is printing.
    * Should solve performance issues
* [x] UI modifications, to make it more streamlined & easier to use
    * [x] Display more helpful error messages (Not Marlin/No EEPROM/Error reading data etc.)
    * [x] Make settings view-only during printing - **requires** python server side storage of data.
* [x] Test compatibility with latest Marlin 
* [x] ~~Sort out version number detection - get numbers for major/minor/patch etc. (remember Marlin 2.x used 4 sections - *e.g. 2.0.5.3*) so that there is less chance of error~~
   In the re-write of this plugin, there is no longer the need to detect versions.

**Comment by dchauran** [comment]
"Test compatibility with latest Marlin"

For me at least, this plugin is completely nonfunctional running marlin from bugfix-2.0.x as of last night, and was nonfunctional when loaded from the old repo as well.

When I change a setting and click upload, it runs m500 but I don't see it actually issuing any command to change the settings I changed. When I click backup, the file only contains:

Send: M504

Recv: echo:EEPROM OK
Recv: ok,Send: M501


I can probably fix these issues, but wanted to make sure you aren't actively looking at them before I dive in.

**Comment by cp2004** [comment]
Hey @dchauran - the backup problem is tracked in #8, I haven't had a chance to dig deep since I am working through implementing the EEPROM stuff in the virtual printer, so I don't have to develop on my production machine for this one. Its almost there, just needs all of the commands now. I'm not actively looking into them *right now* so if you wanted to take a look, by all means go ahead.

**Comment by dchauran** [comment]
thanks, will take the conversation over there
________________________________

**Comment by cp2004** [comment]
Everything on this roadmap is covered for now, as of the release of 3.0.0

Closing, details at #15
